[PORTSORCH] Remove buffer drop counter when port is removed
tomer-israel/sonic-swss pull request #1
Opened 2021-08-03 10:30 UTC by tomer-israel

Signed-off-by: tomeri <tomeri@nvidia.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

2021-08-03 15:40 UTC, dprital requested changes

2021-08-03 15:40 UTC, dprital commented on orchagent/portsorch.cpp
> +
Please remove one line of spacing (please remains with a single line of space)

2021-08-03 15:42 UTC, dprital commented
[PORTSORCH] Remove buffer drop counter when port is removed --> [PORTSORCH] Remove buffer drop counter when port is deleted

2021-08-03 15:48 UTC, dprital approved these changes

2021-08-09 10:48 UTC, closed without merging

2021-08-09 10:48 UTC, tomer-israel commented
going to public PR