Dynamic Port Cfg - VS test
tomer-israel/sonic-swss pull request #12
Opened 2021-11-18 15:18 UTC by tomer-israel

Signed-off-by: tomeri <tomeri@nvidia.com>

**What I did**
added a vs test to check functionality of add/remove ports dynamically on run time

**Why I did it**
in order to test add/remove ports functionality

**How I verified it**
test passed

**Details if related**

2021-11-22 15:52 UTC, stepanblyschak requested changes
General comments:
- avoid time.sleep in VS tests
- Avoid magic numbers in the tests
- Fix code style: trailing newlines, missing spaces in arguments list in function call

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +        config_db.create_entry("PORT",PORT, port_info)
```suggestion
        config_db.create_entry("PORT", PORT, port_info)
```

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +@pytest.mark.usefixtures('dvs_port_manager')
Where is this defined and why do we need it - dvs_port_manager?

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +        for i in range(10):
What is 10?

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
What is the logic behind (i+1)%3 ? Same comment for L104

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
Can we avoid sleep ? Same comment for L104

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            config_db.create_entry("PORT",PORT, port_info)
```suggestion
            config_db.create_entry("PORT", PORT, port_info)
```

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +                config_db.create_entry("PORT",key, ports_info[key])
```suggestion
                config_db.create_entry("PORT", key, ports_info[key])
```

2021-11-22 15:52 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +
remove trailing newlines

2021-11-23 07:34 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +@pytest.mark.usefixtures('dvs_port_manager')
it is defined in the dvs_port.py and conftest.py
used for the function dvs_port.remove_port()

2021-11-23 07:36 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +        for i in range(10):
10 times for adding and removing ports.
I wanted the test to remove and add ports in a loop, since i dont wat the test execution runtime will take too much, 10 times is enough.

2021-11-23 07:37 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
I wanted the sleep time between removing and adding ports will be different in each iteration so I used this calculation

2021-11-23 07:42 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
we need sleep between removing and adding ports - it takes few seconds until all ports are removed/created
since we are using (i+1)%3 we have different timeout for each iteration.
different sleep timeout between add and remove ports can detect bugs, for example we found a bug on LLDP that was reproduced only on specific timeout values

2021-11-23 07:48 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +        config_db.create_entry("PORT",PORT, port_info)
changed

2021-11-23 07:48 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +            config_db.create_entry("PORT",PORT, port_info)
changed

2021-11-23 07:48 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +
removed

2021-11-23 07:48 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +                config_db.create_entry("PORT",key, ports_info[key])
changed

2021-11-23 09:39 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +        config_db.create_entry("PORT",PORT, port_info)
#Resolved

2021-11-23 09:39 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +
#Resolved

2021-11-23 09:39 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +                config_db.create_entry("PORT",key, ports_info[key])
#Resolved

2021-11-23 09:39 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            config_db.create_entry("PORT",PORT, port_info)
#Resolved

2021-11-23 09:40 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +@pytest.mark.usefixtures('dvs_port_manager')
#Resolved

2021-11-23 09:58 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
Is this test case designed to cover some real bug? VS does not have LLDP. How are you detecting those bugs? The only assert I see after sleep is the expectation on the number of SAI_OBJECT_TYPE_PORT objects. It will capture a situation when creation of the port fails in case there is specific sleep time interval after port deletion. Is it even a possible scenario? Can't we just assume that if we successfully deleted the port and the re-creation of the port succeded with 0 sec sleep in between it will work with any sleep interval? What is happening in the system during that sleep that can affect the test case result? The asic.db.wait_for_n_keys will sleep till the entry will appear - will it affect somehow your sleep interval logic?

2021-11-23 09:58 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +        for i in range(10):
I suggest to create a named constant value

2021-11-23 09:59 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +    def test_add_remove_all_the_ports(self, dvs, testlog):
This test case duplicated the code in ```test_add_remove_a_port``` - can we have a single test case that can be parametrized with the number of ports and then parametrize it with 1 port and N ports where N is the total number of ports in the system?

2021-11-23 10:02 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +
Can we reuse part of the DVSPort remove_port ?

2021-11-23 12:33 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +
I want to remove the buffer cfg dependencies without removing the port, the removal of the port will be inside the loop

2021-11-23 12:43 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
this test case is not covering a real bug, the lldp isue that I found was on real switch and it is just an example for race conditions that related to timeouts between delete and create.
I wanted to add several different timeouts between delete and create in order to cover such cases of race conditions that may occur between orchagent and syncd.
I guess that VS switch is not like the real switch and such cases of race conditions will probably be more relevant to real switch.

2021-11-23 12:44 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +        for i in range(10):
will add a constant value

2021-11-23 12:47 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +    def test_add_remove_all_the_ports(self, dvs, testlog):
you right, it's a kind of duplicate code, we can change it but I prefer to leave it as is, in different test cases, one of them is testing only one port and the second one is testing all the ports, I think it will be more readable.

2021-11-23 12:54 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +
Can you create a function in DVSPort - ```remove_port_dependencies``` that will be used here and in ```remove_port``` function?

2021-11-23 12:55 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +
The reason is that in case new dependencies added we need to modify test cases that do  that instaed of modifying one function

2021-11-23 12:58 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
From what I can tell from your comment is that these sleep's are redundant here as  they are relevant for real switch and not for VS.

2021-11-23 14:53 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
I didn't say that, maybe I wasn't clear, I think that race condition can also be on VS switch (maybe on real switch it's more common), that's why the different sleep time in each iteration is relevant also on VS.

2021-11-23 15:03 UTC, tomer-israel commented on tests/test_port_add_remove.py
> +
they are both using the same remove function:
self.dvs_port.remove_port(key) - for removing port dependencies and the port itself

between remove and add port I decided to add different sleep timeouts so a function that will remove and add ports needs to use the I variable inside and it will make the function a bit complex

So I prefer to leave it as is

2021-11-23 15:07 UTC, stepanblyschak commented on tests/test_port_add_remove.py
> +            time.sleep((i+1)%3)
But how are you catching this race condition, where the test fails when you hit it?

2021-11-23 16:54 UTC, stepanblyschak approved these changes

2021-11-24 14:32 UTC, closed without merging