[orchagent] add & remove port counters dynamically each time port was added or removed
tomer-israel/sonic-swss pull request #4
Opened 2021-10-24 12:19 UTC by tomer-israel

**What I did**
add support for adding & removing port counters dynamically each time port was added or removed
the counters that were supported are:
- pg watermark counters
- pg drop counters
- queue stat counters
- queue watermark counters
- debug counters

* buffer drop counters and port stat counters are already supported to be added or removed each time port  is added/removed

**Why I did it**
in order to support dynamically add or removed ports on sonic

**How I verified it**
tested manually that the flex counters were added or removed correctly whenever we add or remove ports
added new test cases to the following vs tests:
- test_flex_counters.py
- test_drop_counters.py
- test_pg_drop_counter.py

**Details if related**

2021-10-27 09:29 UTC, stepanblyschak requested changes

2021-10-31 13:12 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +    if (!getPort(port_id, p))
will be changed

2021-10-31 13:13 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +    /* Add stat counters to flex_counter */
will be removed

2021-10-31 13:16 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +        // Install a flex counter for this queue to track stats
will be removed

2021-10-31 13:18 UTC, tomer-israel commented on orchagent/debugcounterorch.cpp
> +    for (auto it = debug_counters.begin(); it != debug_counters.end(); it++) {
changed

2021-10-31 13:19 UTC, tomer-israel commented on orchagent/debugcounterorch.cpp
> +        DebugCounter *counter = dynamic_cast<DebugCounter*>(it->second.get());
changed

2021-10-31 13:23 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +    for (size_t queueIndex = 0; queueIndex < port.m_queue_ids.size(); ++queueIndex)
i dont understand.
this loop was taken from the add command (not new code)

2021-10-31 13:23 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +        // Install a flex counter for this queue to track stats
removed

2021-10-31 13:25 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +        /* add watermark queue counters */
this comment is relevant for the generatePriorityGroupMapPerPort function in the removePriorityGroupMapPerPort i will change it to remove watermark queue...

2021-10-31 13:32 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +    CounterCheckOrch::getInstance().removePort(port);
it's possible, i just wanted to follow the current implementation. in the generatePriorityGroupMapPerPort function we are using:
CounterCheckOrch::getInstance().addPort(port);
so in the remove function we will use:
CounterCheckOrch::getInstance().removePort(port);

2021-10-31 21:24 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +
will be changed

2021-11-01 08:21 UTC, tomer-israel commented on tests/test_flex_counters.py
> +                break
i changed it to while loop - break loop when queue id dont exist

2021-11-01 11:36 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +    CounterCheckOrch::getInstance().removePort(port);
I will leave it like that since the add function is doing the same (addPort).
refactor the generate function and the remove function will take too much effort for now

2021-11-01 15:36 UTC, tomer-israel commented on tests/test_drop_counters.py
> +        time.sleep(5)
added

2021-11-02 10:39 UTC, stepanblyschak commented on orchagent/debugcounterorch.cpp
> +
reduntand empty line

2021-11-02 11:36 UTC, stepanblyschak commented on tests/test_flex_counters.py
> +                break
This code looks too verbose and very C-style which makes it hard to understand without comments. Can we do this:

```python
oid_list = [oid for port_queue, oid in counters_queue_map.values() if port_queue.startswith(PORT)]
```

Which is self-explanatory: collect every oid in counters_queue_map if this oid belongs to PORT.

2021-11-02 11:36 UTC, stepanblyschak commented on tests/test_drop_counters.py
> +import redis
Do we need redis still?

2021-11-02 12:56 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +                SWSS_LOG_ERROR("Failed to get port object for port id 0x%" PRIx64 " - its ok to ignore this message if this port was just removed", id);
this will be removed

2021-11-02 13:40 UTC, tomer-israel commented on tests/test_flex_counters.py
> +                break
i changed it to simpler for loop

2021-11-02 13:41 UTC, tomer-israel commented on tests/test_flex_counters.py
> +                break
I changed it to simpler for loop.
one line loop as you suggested can be hard to understand and the for loop is simplier

2021-11-02 14:09 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                SWSS_LOG_ERROR("Failed to get port object for port id 0x%" PRIx64 ", id);
"Failed to get port object for port id 0x%" PRIx64 "
The last " is redundant?

2021-11-02 14:09 UTC, stepanblyschak commented on orchagent/portsorch.cpp
> +                SWSS_LOG_ERROR("Failed to get port object for port id 0x%" PRIx64 ", id);
Now I am confused with this.
Originally, there was a comment saying it is actually a notice not an error. So I am wondering, if we catch this error in our regression tests - the test will fail?

2021-11-02 14:09 UTC, stepanblyschak commented on tests/test_drop_counters.py
> +
Still see trailing spaces

2021-11-02 14:10 UTC, stepanblyschak commented on tests/test_flex_counters.py
> +                break
It is very common to see such list comprehension syntax in python. But this is IMO. Ok, if that is simpler for-loop

2021-11-02 14:11 UTC, stepanblyschak commented on orchagent/orchdaemon.cpp
> +DebugCounterOrch *gDebugCounterOrch;
Is this addressed?

2021-11-02 15:16 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +                SWSS_LOG_ERROR("Failed to get port object for port id 0x%" PRIx64 ", id);
after discussion with Dror we decided to add this change in a differetn PR since it's not really related to the counters changes.

2021-11-02 15:26 UTC, tomer-israel commented on tests/test_flex_counters.py
> +        for oid in oid_list:
you right it's empty, i forgot to add the oid to the oid_list in the previous for loop
i fixed it

2021-11-02 15:27 UTC, tomer-israel commented on orchagent/portsorch.cpp
> +                SWSS_LOG_ERROR("Failed to get port object for port id 0x%" PRIx64 ", id);
i revert it to original code.
this change will be pushed in a different PR since it is not related to counters changes

2021-11-02 15:40 UTC, stepanblyschak approved these changes

2021-11-09 16:17 UTC, tomer-israel commented
close and create external PR

2021-11-09 16:17 UTC, closed without merging